version: "3"
services:
  centro_distribuicao:
    build: .
    command: python3 -u centro_distribuicao.py
  fabrica:
    build: .
    command: python3 -u fabrica.py
    deploy:
      mode: replicated
      replicas: 2
  loja:
    build: .
    command: python3 -u loja.py
    deploy:
      mode: replicated
      replicas: 2
  web:
    build: .
    command: python3 -u app.py
    ports:
      - "5000:5000"
